CREATE TABLE wishful_revelations (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    revelation_text TEXT NOT NULL,
    is_prediction_correct BOOLEAN NOT NULL,
    evidence TEXT NOT NULL,
    prediction_id INTEGER REFERENCES wishful_predictions(id) ON DELETE CASCADE NOT NULL,
    user_id INTEGER REFERENCES wishful_users(id) ON DELETE CASCADE NOT NULL,
    revealed_at TIMESTAMP DEFAULT now()
);