CREATE TABLE wishful_comments (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content TEXT NOT NULL,
    user_id INTEGER REFERENCES wishful_users(id) ON DELETE CASCADE NOT NULL,
    prediction_id INTEGER REFERENCES wishful_predictions(id) ON DELETE CASCADE NOT NULL,
    commented_at TIMESTAMP DEFAULT now()
);